# Use this file to override the docker-compose.librechat.yml file to enable local builds from dev/ submodules
# docker-compose will automatically use this file when present

services:
  api:
    image: librechat:local
    build:
      context: ./dev/librechat
      dockerfile: Dockerfile
      target: node
    volumes:
      - ./dev/agents/dist:/app/node_modules/@librechat/agents/dist

  rag_api:
    image: rag_api:local
    build:
      context: ./dev/rag_api
      dockerfile: Dockerfile


