roles:
  - name: DEVELOPER
    permissions:
      PROMPTS:
        SHARED_GLOBAL: true
        USE: true
        CREATE: true
      AGENTS:
        SHARED_GLOBAL: true
        USE: true
        CREATE: true
      MEMORIES:
        USE: true
        CREATE: true
        UPDATE: true
        READ: true
        OPT_OUT: true
      BOOKMARKS:
        USE: true
      WEB_SEARCH:
        USE: true
      PEOPLE_PICKER:
        VIEW_USERS: true
        VIEW_GROUPS: true
        VIEW_ROLES: true
      MARKETPLACE:
        USE: true
      MCP_SERVERS:
        USE: true
        CREATE: true
        SHARE: true
      FILE_SEARCH:
        USE: true
      FILE_CITATIONS:
        USE: true
      RUN_CODE:
        USE: true
      MULTI_CONVO:
        USE: true
      TEMPORARY_CHAT:
        USE: true
